//
// Generated file, do not edit! Created by nedtool 6.0 from RfPhyPacket.msg.
//

#ifndef __RFPHYPACKET_M_H
#define __RFPHYPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif




namespace omnetpp {

}  // namespace omnetpp

#endif // ifndef __RFPHYPACKET_M_H

