function javi

data = importfile('outputLossMat_Uniforme.txt');

data = data.outputLossMat_Uniforme;
[a,b] = find(data==-1000);
for i = 1:length(a)
data(a(i),b(i))=NaN;
end
close all
surf(data);


Lmax = -3 +54 - 25;

Lmax = 33; % Cancellation CS-COMB
Lmax = 40
% Lmax = 26;  % for imp noise
Lmax = 48; % for bkg
plano=-Lmax*ones(size(data));
hold on

h = surf(plano);
set(h,'FaceColor','none')
set(h,'EdgeColor',[0 0 1])



ylim=get(get(h,'Parent'),'ZLim');
attOK = NaN*ones(size(data));
nHosts = size(data,1);
txvect=[];
rxvect=[];
for txIndex=1:nHosts
    for rxIndex=1:nHosts
        if data(txIndex,rxIndex)>-Lmax
            attOK(txIndex,rxIndex)=min(ylim);
            txvect=[txvect txIndex];
            rxvect=[rxvect rxIndex];
        end
    end
end
hold on
plot3(rxvect,txvect,min(ylim)*ones(1,length(txvect)),'.')
figure
plot(txvect,rxvect,'.')
xlabel('txFrom'),
ylabel('rxAt')
grid on
title('Conexiones en menos de la atenuacion maxima');

function newData1 = importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 16-Sep-2013 11:38:20

% Import the file
rawData1 = importdata(fileToRead1);

% For some simple files (such as a CSV or JPEG files), IMPORTDATA might
% return a simple array.  If so, generate a structure so that the output
% matches that from the Import Wizard.
[~,name] = fileparts(fileToRead1);
newData1.(genvarname(name)) = rawData1;

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

